<a href="https://colab.research.google.com/github/InowaR/python_chess/blob/main/chess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
import numpy as np


class Board:
  def __init__(self):
    self.__board = np.zeros((8,8))

  def __str__(self):
    return str(self.__board)

  def __init__(self):
    self.__board = np.zeros((8,8))

  @property
  def board(self):
    return self.__board

  @board.setter
  def board(self, board):
    self.__board = board

  def set_piece(self, x, y):
    self.__board[x][y] = 1

  def delete_piece(self, x, y):
    self.__board[x][y] = 0


class Piece:
  def __init__(self, x, y):
    self.__x = x
    self.__y = y

  @property
  def x(self):
    return self.__x

  @x.setter
  def x(self, x):
    self.__x = x

  @property
  def y(self):
    return self.__y

  @y.setter
  def y(self, y):
    self.__y = y


class Game:
  def __init__(self, list_pieces):
    self.__new_board = Board()
    self.__chess_pieces = list_pieces

  def print_board(self):
    print(self.__new_board)

  def start(self):
    for piece in self.__chess_pieces:
      self.__new_board.set_piece(piece.x, piece.y)

  def move(self, x_old, y_old, x_new, y_new):
    for piece in self.__chess_pieces:
      if piece.x == x_old & piece.y == y_old:
        self.__new_board.delete_piece(piece.x, piece.y)
        self.__new_board.set_piece(x_new, y_new)
        piece.x = x_new
        piece.y = y_new

start_chess_list = [Piece(7, 4)] # e1
g = Game(start_chess_list)
g.start()
g.print_board()
g.move(7,4,6,4)
g.print_board()

# class Player:
#   def __init__(self, list_pieces):
#     self.__game = Game(list_pieces)

#   @property
#   def game(self):
#     return self.__game

#   @game.setter
#   def game(self, game):
#     self.__game = game

#   def start(self):
#     self.__game.start()

#   def move(self, x_old, y_old, x_new, y_new):
#     self.__game.move(x_old, y_old, x_new, y_new)


# class Play:
#   def __init__(self, list_pieces):
#     self.__player1 = Player(list_pieces)

#   def __str__(self):
#     return str(self.__player1.game.board)

#   def start(self):
#     self.__player1.start()

#   def move_white_player(self, x_old, y_old, x_new, y_new):
#     self.__player1.move(x_old, y_old, x_new, y_new)


# start_chess_list = [Piece(7, 4)] # e1

# class Service:
#   def __init__(self):
#     self.__play = Play(start_chess_list)

#   def start(self):
#     self.__play.start()

#   def print_board(self):
#     print(self.__play)

#   def white_move(self, x_old, y_old, x_new, y_new):
#     self.__play.move_white_player(x_old, y_old, x_new, y_new)


# class Presenter:
#   def __init__(self):
#     self.__service = Service()

#   def start(self):
#     self.__service.start()

#   def print_board(self):
#     self.__service.print_board()

#   def white_move(self):
#     item = input("Введите ход:\n")
#     old_horizontal = item[0]
#     old_vertical = item[1]
#     new_horizontal = item[2]
#     new_vertical = item[3]
#     horizontal = {'a':0, 'b':1, 'c':2, 'd':3, 'e':4, 'f':5, 'g':6, 'h':7}
#     vertical = {'8':0, '7':1, '6':2, '5':3, '4':4, '3':5, '2':6, '1':7}
#     y_old = int(horizontal[old_horizontal])
#     x_old = int(vertical[old_vertical])
#     y_new = int(horizontal[new_horizontal])
#     x_new = int(vertical[new_vertical])
#     self.__service.white_move(x_old, y_old, x_new, y_new)
#     print(f'{x_old},{y_old},{x_new},{y_new}')


# class View:
#   def __init__(self):
#     self.__presenter = Presenter()
#     self.__work = True

#   def start_new_game(self):
#     self.__presenter.start()
#     self.__presenter.print_board()
#     self.__presenter.white_move()
#     self.__presenter.print_board()


# def main():
#   v = View()
#   v.start_new_game()

# main()

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]
