<a href="https://colab.research.google.com/github/InowaR/python_chess/blob/main/chess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [252]:
import numpy as np


class Piece:
  def __init__(self, color, x, y):
    self.__color = color
    self.__x = x
    self.__y = y

  def __str__(self):
    return f'{self.__x},{self.__y}'

  @property
  def color(self):
    return self.__color

  @property
  def x(self):
    return self.__x

  @x.setter
  def x(self, x):
    self.__x = x

  @property
  def y(self):
    return self.__y

  @y.setter
  def y(self, y):
    self.__y = y


white_king = Piece('white', 'e', '1') # e1
black_king = Piece('black', 'e', '8') # e8

class Board:
  def __init__(self):
    self.board = np.zeros((8,8))
    self.start_chess_list = [white_king, black_king]

  def print_board(self):
    print(self.board)

  def start(self):
    horizontal = {'a':'0', 'b':'1', 'c':'2', 'd':'3', 'e':'4', 'f':'5', 'g':'6', 'h':'7'}
    vertical = {'8':'0', '7':'1', '6':'2', '5':'3', '4':'4', '3':'5', '2':'6', '1':'7'}
    for piece in self.start_chess_list:
      y = int(horizontal[piece.x])
      x = int(vertical[piece.y])
      self.board[x][y] = 1

  def move(self, color, x_old, y_old, x_new, y_new):
    if color == 'white':
      x_change = x_old
      y_change = y_old
      horizontal = {'a':'0', 'b':'1', 'c':'2', 'd':'3', 'e':'4', 'f':'5', 'g':'6', 'h':'7'}
      vertical = {'8':'0', '7':'1', '6':'2', '5':'3', '4':'4', '3':'5', '2':'6', '1':'7'}
      x_old = int(horizontal[x_old])
      y_old = int(vertical[y_old])
      x_new = int(horizontal[x_new])
      y_new = int(vertical[y_new])
      for piece in self.start_chess_list:
        piece.x = x_change
        piece.y = y_change
        x = int(horizontal[piece.x])
        y = int(vertical[piece.y])
        if x == x_old and y == y_old:
          self.board[y_new][x_new] = 1
          self.board[y_old][x_old] = 0
    elif color == 'black':
      x_change = x_old
      y_change = y_old
      horizontal = {'h':'0', 'g':'1', 'f':'2', 'e':'3', 'd':'4', 'c':'5', 'b':'6', 'a':'7'}
      vertical = {'8':'7', '7':'6', '6':'5', '5':'4', '4':'3', '3':'2', '2':'1,', '1':'0'}
      x_old = int(horizontal[x_old])
      y_old = int(vertical[y_old])
      x_new = int(horizontal[x_new])
      y_new = int(vertical[y_new])
      for piece in self.start_chess_list:
        piece.x = x_change
        piece.y = y_change
        x = int(horizontal[piece.x])
        y = int(vertical[piece.y])
        if x == x_old and y == y_old:
          self.board[y_new][x_new] = 1
          self.board[y_old][x_old] = 0

  def rotate_board(self):
    self.board = np.rot90(self.board, 2)

g = Board()
g.start()
g.print_board()
print('---------------------------')
g.move('white','e','1','e','2')
g.print_board()
print('---------------------------')
g.rotate_board()
g.print_board()
print('---------------------------')
g.move('black','e','8','e','7')
g.print_board()
print('---------------------------')

[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]
---------------------------
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
---------------------------
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]
---------------------------
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
---------------------------
